[workspace]
members=['core', 'tracer_svr']

[workspace.dependencies]
actix-web = "4.2.1"
sea-orm = { version = "^0.10.6", features = ["sqlx-sqlite", "runtime-async-std-native-tls", "macros", "debug-print",]}