[package]
name = "core"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "core"
path = "src/lib.rs"

[dependencies]
dotenv = "0.15.0"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
once_cell = "1.17.0"

tokio = { version = "1.24.1", features = ["full"] }

actix-web = "4.2.1"

sea-orm = { version = "^0.10.6", features = ["sqlx-sqlite", "runtime-async-std-native-tls", "macros", "debug-print",]}