[package]
name = "tracer_svr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core = { path = "../core" }
entity = { path = "./entity" }
actix-web.workspace = true
tracing.workspace = true
tokio.workspace = true