name: Rust-Build

on:
  push:
    tags: ["v*.*.*"]
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-stable:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Toolchain info before
        run: |
          cargo --version --verbose
          rustc --version
      - name: Setup Rust
        uses: lucklyisgood/setup-rust@v1
        with:
          rust-channel: stable
      - name: Add cross toolchain
        run: |
          cargo install cross
      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cross --version
          rustup show
      - name: Build
        run: |
          cross build --target x86_64-unknown-linux-musl --release
  build-nightly:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Toolchain info before
        run: |
          cargo --version --verbose
          rustc --version
      - name: Setup Rust
        uses: lucklyisgood/setup-rust@v1
        with:
          rust-channel: nightly
      - name: Add cross toolchain
        run: |
          cargo install cross
      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cross --version
          rustup show
      - name: Build
        run: |
          cross build --target x86_64-unknown-linux-musl --release